controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    camera_link_controller:
      type: forward_command_controller/ForwardCommandController


camera_link_controller:
  ros__parameters:
    joints: 
      - camera_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
        
